import React, {useState, createContext} from 'react'

export const SeatContext = createContext();

export const SeatProvider = props => {
    const [seats, setSeats] = useState(
        [
            //Level 2
            {
                id: 1,
                level: 2,
                seatName: 'L2S1',
                cameraId: 'L2C1',
                x1Img: 45,
                y1Img: 45,
                x2Img: 65,
                y2Img: 65,
                xLoc: 25,
                yLoc: 50,
                status: 'Available',
                unavailable:false
            },
            {
                id: 2,
                level: 2,
                seatName: 'L2S2',
                cameraId: 'L2C1',
                x1Img: 145,
                y1Img: 45,
                x2Img: 165,
                y2Img: 65,
                xLoc: 105,
                yLoc: 150,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 3,
                level: 2,
                seatName: 'L2S3',
                cameraId: 'L2C1',
                x1Img: 245,
                y1Img: 45,
                x2Img: 265,
                y2Img: 65,
                xLoc: 500,
                yLoc: 650,
                status: 'Occupied',
                unavailable:false
            },
            {
                id: 4,
                level: 2,
                seatName: 'L2S4',
                cameraId: 'L2C1',
                x1Img: 345,
                y1Img: 45,
                x2Img: 365,
                y2Img: 65,
                xLoc: 100,
                yLoc: 450,
                status: 'Hogged',
                unavailable:false
            },
            {
                id: 5,
                level: 2,
                seatName: 'L2S5',
                cameraId: 'L2C1',
                x1Img: 445,
                y1Img: 45,
                x2Img: 465,
                y2Img: 65,
                xLoc: 500,
                yLoc: 160,
                status: 'Available',
                unavailable:false
            },
            {
                id: 6,
                level: 2,
                seatName: 'L2S6',
                cameraId: 'L2C1',
                x1Img: 545,
                y1Img: 45,
                x2Img: 565,
                y2Img: 65,
                xLoc: 600,
                yLoc: 150,
                status: 'Available',
                unavailable:false
            },
            {
                id: 7,
                level: 2,
                seatName: 'L2S7',
                cameraId: 'L2C1',
                x1Img: 645,
                y1Img: 45,
                x2Img: 665,
                y2Img: 65,
                xLoc: 300,
                yLoc: 300,
                status: 'Available',
                unavailable:false
            },
            {
                id: 8,
                level: 2,
                seatName: 'L2S8',
                cameraId: 'L2C1',
                x1Img: 45,
                y1Img: 145,
                x2Img: 65,
                y2Img: 165,
                xLoc: 400,
                yLoc: 650,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 9,
                level: 2,
                seatName: 'L2S9',
                cameraId: 'L2C1',
                x1Img: 145,
                y1Img: 145,
                x2Img: 165,
                y2Img: 165,
                xLoc: 200,
                yLoc: 650,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 10,
                level: 2,
                seatName: 'L2S10',
                cameraId: 'L2C1',
                x1Img: 245,
                y1Img: 145,
                x2Img: 265,
                y2Img: 165,
                xLoc: 700,
                yLoc: 650,
                status: 'Reserved',
                unavailable:false
            },
            //Level 3
            {
                id: 11,
                level: 3,
                seatName: 'L3S11',
                cameraId: 'L3C1',
                x1Img: 45,
                y1Img: 45,
                x2Img: 65,
                y2Img: 65,
                xLoc: 700,
                yLoc: 350,
                status: 'Available',
                unavailable:false
            },
            {
                id: 12,
                level: 3,
                seatName: 'L3S12',
                cameraId: 'L3C1',
                x1Img: 145,
                y1Img: 45,
                x2Img: 165,
                y2Img: 65,
                xLoc: 470,
                yLoc: 470,
                status: 'Occupied',
                unavailable:false
            },
            {
                id: 13,
                level: 3,
                seatName: 'L3S13',
                cameraId: 'L3C1',
                x1Img: 245,
                y1Img: 45,
                x2Img: 265,
                y2Img: 65,
                xLoc: 190,
                yLoc: 470,
                status: 'Occupied',
                unavailable:false
            },
            {
                id: 14,
                level: 3,
                seatName: 'L3S14',
                cameraId: 'L3C1',
                x1Img: 345,
                y1Img: 45,
                x2Img: 365,
                y2Img: 65,
                xLoc: 670,
                yLoc: 270,
                status: 'Occupied',
                unavailable:false
            },
            {
                id: 15,
                level: 3,
                seatName: 'L3S15',
                cameraId: 'L3C1',
                x1Img: 445,
                y1Img: 45,
                x2Img: 465,
                y2Img: 65,
                xLoc: 730,
                yLoc: 160,
                status: 'Occupied',
                unavailable:false
            },
            //Level 4
            {
                id: 16,
                level: 4,
                seatName: 'L4S16',
                cameraId: 'L4C1',
                x1Img: 45,
                y1Img: 45,
                x2Img: 65,
                y2Img: 65,
                xLoc: 123,
                yLoc: 134,
                status: 'Unavailable',
                unavailable:true
            },
            {
                id: 17,
                level: 4,
                seatName: 'L4S17',
                cameraId: 'L4C1',
                x1Img: 145,
                y1Img: 45,
                x2Img: 165,
                y2Img: 65,
                xLoc: 163,
                yLoc: 273,
                status: 'Available',
                unavailable:false
            },
            {
                id: 18,
                level: 4,
                seatName: 'L4S18',
                cameraId: 'L4C1',
                x1Img: 245,
                y1Img: 45,
                x2Img: 265,
                y2Img: 65,
                xLoc: 235,
                yLoc: 47,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 19,
                level: 4,
                seatName: 'L4S19',
                cameraId: 'L4C1',
                x1Img: 345,
                y1Img: 45,
                x2Img: 365,
                y2Img: 65,
                xLoc: 436,
                yLoc: 631,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 20,
                level: 4,
                seatName: 'L4S20',
                cameraId: 'L4C1',
                x1Img: 445,
                y1Img: 45,
                x2Img: 465,
                y2Img: 65,
                xLoc: 643,
                yLoc: 362,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 21,
                level: 4,
                seatName: 'L4S21',
                cameraId: 'L4C1',
                x1Img: 545,
                y1Img: 45,
                x2Img: 565,
                y2Img: 65,
                xLoc: 623,
                yLoc: 634,
                status: 'Unavailable',
                unavailable:true
            },
            {
                id: 22,
                level: 4,
                seatName: 'L4S22',
                cameraId: 'L4C1',
                x1Img: 645,
                y1Img: 45,
                x2Img: 665,
                y2Img: 65,
                xLoc: 163,
                yLoc: 673,
                status: 'Available',
                unavailable:false
            },
            {
                id: 23,
                level: 4,
                seatName: 'L4S23',
                cameraId: 'L4C1',
                x1Img: 45,
                y1Img: 145,
                x2Img: 65,
                y2Img: 165,
                xLoc: 435,
                yLoc: 347,
                status: 'Available',
                unavailable:false
            },
            {
                id: 24,
                level: 4,
                seatName: 'L4S24',
                cameraId: 'L4C1',
                x1Img: 45,
                y1Img: 145,
                x2Img: 65,
                y2Img: 165,
                xLoc: 436,
                yLoc: 231,
                status: 'Available',
                unavailable:false
            },
            {
                id: 25,
                level: 4,
                seatName: 'L4S25',
                cameraId: 'L4C1',
                x1Img: 145,
                y1Img: 145,
                x2Img: 165,
                y2Img: 165,
                xLoc: 146,
                yLoc: 362,
                status: 'Reserved',
                unavailable:false
            },
            //Level 5
            {
                id: 26,
                level: 5,
                seatName: 'L4S26',
                cameraId: 'L5C1',
                x1Img: 45,
                y1Img: 45,
                x2Img: 65,
                y2Img: 65,
                xLoc: 236,
                yLoc: 532,
                status: 'Available',
                unavailable:false
            },
            {
                id: 27,
                level: 5,
                seatName: 'L4S27',
                cameraId: 'L5C1',
                x1Img: 145,
                y1Img: 45,
                x2Img: 165,
                y2Img: 65,
                xLoc: 462,
                yLoc: 125,
                status: 'Reserved',
                unavailable:false
            },
            {
                id: 28,
                level: 5,
                seatName: 'L4S28',
                cameraId: 'L5C1',
                x1Img: 245,
                y1Img: 45,
                x2Img: 265,
                y2Img: 65,
                xLoc: 643,
                yLoc: 213,
                status: 'Hogged',
                unavailable:false
            },
            {
                id: 29,
                level: 5,
                seatName: 'L4S29',
                cameraId: 'L5C1',
                x1Img: 345,
                y1Img: 45,
                x2Img: 365,
                y2Img: 65,
                xLoc: 463,
                yLoc: 416,
                status: 'Hogged',
                unavailable:false
            },
            {
                id: 30,
                level: 5,
                seatName: 'L4S30',
                cameraId: 'L5C1',
                x1Img: 45,
                y1Img: 45,
                x2Img: 65,
                y2Img: 65,
                xLoc: 213,
                yLoc: 362,
                status: 'Reserved',
                unavailable:false
            },
        ]);
    
    return (
        <SeatContext.Provider value={[seats, setSeats]}>
            {props.children}
        </SeatContext.Provider>
    )
}